# Generated by Django 5.0.1 on 2025-06-20 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP地址')),
                ('department', models.CharField(max_length=50, verbose_name='部门')),
                ('smb_username', models.CharField(max_length=50, verbose_name='SMB用户名')),
                ('smb_password', models.CharField(max_length=100, verbose_name='SMB密码')),
                ('remote_path', models.CharField(help_text='格式：\\\\IP或主机名\\共享文件夹\\子目录', max_length=255, verbose_name='远程共享路径')),
                ('local_path', models.CharField(help_text='格式：\\backup\\recordings', max_length=255, verbose_name='备份路径')),
                ('status', models.CharField(choices=[('online', '在线'), ('syncing', '同步中'), ('offline', '离线')], default='offline', max_length=10, verbose_name='状态')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('file_count', models.PositiveIntegerField(default=0, verbose_name='同步文件数量')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='record_syn.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '同步记录',
                'verbose_name_plural': '同步记录',
                'ordering': ['-record_time'],
            },
        ),
    ]
