# Generated by Django 5.0.1 on 2025-06-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_syn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('log_type', models.CharField(choices=[('info', '信息'), ('error', '错误')], max_length=10, verbose_name='日志类型')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record_syn.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '同步日志',
                'verbose_name_plural': '同步日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
