# Generated by Django 5.0.1 on 2025-06-27 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_syn', '0002_synclog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncrecord',
            options={'ordering': ['-start_time'], 'verbose_name': '同步记录', 'verbose_name_plural': '同步记录'},
        ),
        migrations.RemoveField(
            model_name='syncrecord',
            name='record_time',
        ),
        migrations.AddField(
            model_name='syncrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='syncrecord',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
