# Generated by Django 5.0.1 on 2025-06-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_syn', '0003_alter_syncrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrecord',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
