# Generated by Django 5.0.1 on 2025-06-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_syn', '0004_syncrecord_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncrecord',
            name='message',
        ),
    ]
